name: practice input


on:
 workflow_dispatch:
  inputs:
    environment:
     description: "select Environment"
     default: "dev"
     required: true
     type: choice
     options:
         - dev
         - prod
         - staging
  
